CREATE TABLE IF NOT EXISTS cliente
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(255),
    cpf             VARCHAR(11),
    email           VARCHAR(20),
    telefone        VARCHAR(11),
    cnpj            VARCHAR(14),
    nome_empresa    VARCHAR(255),
    plano_pagamento VARCHAR(8),
    saldo           DECIMAL,
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS destinatario
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(255),
    telefone    VARCHAR(11)                             NOT NULL,
    mensagem_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_destinatario PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS mensagem
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero_telefone VARCHAR(11),
    whats_app       BOOLEAN                                 NOT NULL,
    mensagem        VARCHAR(255),
    cliente_id      BIGINT,
    CONSTRAINT pk_mensagem PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS transacao
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valor          DECIMAL,
    data           date,
    tipo_transacao VARCHAR(7)                              NOT NULL,
    descricao      VARCHAR(255),
    cliente_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_transacao PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS administrador
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255),
    senha VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_administrador PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS destinatario
    ADD CONSTRAINT FK_DESTINATARIO_ON_MENSAGEM FOREIGN KEY (mensagem_id) REFERENCES mensagem (id);

ALTER TABLE IF EXISTS mensagem
    ADD CONSTRAINT FK_MENSAGEM_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES cliente (id);

ALTER TABLE IF EXISTS transacao
    ADD CONSTRAINT FK_TRANSACAO_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES cliente (id);